version: "3.9"

services:
  nginx:
    container_name: ts-nginx
    image: nginx:alpine
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ".:/var/www/html/"
      - "./infrastructure/dev/nginx/etc/conf.d/:/etc/nginx/conf.d/"
      - "./infrastructure/dev/nginx/etc/ssl/:/etc/nginx/ssl/"
      - "./infrastructure/dev/nginx/etc/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ts-network

  php:
    image: taygeta/php:8.2
    container_name: ts-php
    environment:
      TZ: "Europe/Moscow"
      PHP_IDE_CONFIG: "serverName=docker"
      XDG_CACHE_HOME: "/var/www/html/var/"
      COMPOSER_HTACCESS_PROTECT: "0"
      YARN_CACHE_FOLDER: "/var/www/html/var/"
      NODE_REPL_HISTORY: "/var/www/html/var/.node_repl_history"
      NLS_LANG: "Russian_Russia.UTF8"
    volumes:
      - ".:/var/www/html/"
      - "./infrastructure/dev/php/etc/php/php.ini:/usr/local/etc/php/php.ini"
      - "./infrastructure/dev/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
    depends_on:
      - db
    networks:
      - ts-network
    extra_hosts:
      - "registry.yarnpkg.com:104.16.16.35"

  db:
    image: taygeta/pgpro:14
    container_name: ts-db
    volumes:
      - "data:/var/lib/pgpro/std-14/data/"
      - "./infrastructure/dev/postgrespro/etc/postgresql.conf:/var/lib/pgpro/std-14/data/postgresql.conf"
      - "./infrastructure/dev/postgrespro/etc/pg_hba.conf:/var/lib/pgpro/std-14/data/pg_hba.conf"
      - "./infrastructure/dev/postgrespro/etc/pg_ident.conf:/var/lib/pgpro/std-14/data/pg_ident.conf"
    ports:
      - "5432:5432"
    networks:
      - ts-network

networks:
  ts-network:

volumes:
  data:
